version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # LocalStack edge port
    environment:
      - SERVICES=sns,sqs,dynamodb
      - DEBUG=1
      #- LEGACY_SQS_URLS=true
      - DATA_DIR=/tmp/localstack/data
    volumes:
      #- "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"